export enum Role {
  USER = 'user',
  MODEL = 'model'
}

export interface UserPreferences {
  notifications: boolean;
  highContrast: boolean;
  theme: 'light' | 'dark';
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  xp: number;
  level: number;
  preferences: UserPreferences;
  createdAt: number;
  passwordHash?: string; // Hash da senha (opcional para compatibilidade)
}

export interface Attachment {
  type: 'image';
  content: string; // Base64
  mimeType: string;
}

export interface Message {
  id: string;
  role: Role;
  text: string;
  attachment?: Attachment; // Image sent by user
  generatedImage?: string; // Image generated by AI (Base64)
  timestamp: number;
}

export interface ChatSession {
  id: string;
  title: string;
  domainId: DomainId;
  messages: Message[];
  createdAt: number;
  userId: string; // Link session to user
}

// Novos tipos para memória contextual
export interface UserMemoryEntry {
  id: string;
  userId: string;
  type: 'interest' | 'knowledge_level' | 'preference' | 'goal' | 'context';
  category: string; // ex: 'programming', 'learning_style', 'project'
  key: string; // ex: 'favorite_language', 'experience_level', 'current_project'
  value: string; // ex: 'Python', 'beginner', 'e-commerce website'
  confidence: number; // 0-1, quão confiante estamos nesta informação
  lastUpdated: number;
  expiresAt?: number; // Para informações temporárias
}

export interface UserProfile {
  userId: string;
  knowledgeLevel: Record<DomainId, 'beginner' | 'intermediate' | 'advanced'>;
  interests: string[]; // Tópicos de interesse
  learningStyle: 'visual' | 'auditory' | 'kinesthetic' | 'reading' | 'mixed';
  goals: string[]; // Objetivos de aprendizado
  frequentTopics: Record<string, number>; // Tópico -> frequência
  lastActive: number;
  totalSessions: number;
  averageSessionLength: number;
}

export interface ContextualMemory {
  shortTerm: Message[]; // Últimas mensagens da sessão atual
  mediumTerm: UserMemoryEntry[]; // Informações da última semana
  longTerm: UserProfile; // Perfil consolidado do usuário
}

export enum DomainId {
  PROGRAMMING = 'programming',
  CONSULTING = 'consulting',
  THEOLOGY = 'theology',
  AGRICULTURE = 'agriculture',
  ACCOUNTING = 'accounting',
  PSYCHOLOGY = 'psychology',
}

export interface DomainConfig {
  id: DomainId;
  name: string;
  icon: string;
  color: string; // Tailwind text color class
  bgColor: string; // Tailwind bg color class
  description: string;
  systemPrompt: string;
}