export enum Role {
  USER = 'user',
  MODEL = 'model'
}

export interface UserPreferences {
  notifications: boolean;
  highContrast: boolean;
  theme: 'light' | 'dark';
  language: 'pt-BR' | 'en-US';
}

export interface OnboardingData {
  // Como conheceu a plataforma
  discoverySource: 'google_search' | 'social_media' | 'friend_recommendation' | 'advertisement' | 'blog_article' | 'youtube' | 'other';
  discoverySourceDetails?: string; // Detalhes se "other" ou informações adicionais
  
  // Objetivo principal
  primaryGoal: 'learning' | 'work_assistance' | 'research' | 'entertainment' | 'productivity' | 'other';
  primaryGoalDetails?: string;
  
  // Área de interesse principal
  primaryInterest: DomainId;
  
  // Nível de experiência
  experienceLevel: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  
  // Profissão/área de atuação
  profession?: string;
  
  // Expectativas
  expectations: string[];
  
  // Frequência de uso pretendida
  expectedUsage: 'daily' | 'weekly' | 'monthly' | 'occasionally';
  
  // Dispositivo principal
  primaryDevice: 'desktop' | 'mobile' | 'tablet' | 'mixed';
  
  // Dados demográficos opcionais
  ageRange?: '18-24' | '25-34' | '35-44' | '45-54' | '55-64' | '65+';
  location?: string; // País/região
  
  // Feedback inicial
  initialFeedback?: string;
  
  // Timestamp
  completedAt: number;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  xp: number;
  level: number;
  preferences: UserPreferences;
  createdAt: number;
  passwordHash?: string; // Hash da senha (opcional para compatibilidade)
  onboarding?: OnboardingData; // Dados de onboarding
  hasCompletedOnboarding?: boolean; // Flag para saber se completou
}

export interface Attachment {
  type: 'image';
  content: string; // Base64
  mimeType: string;
}

export interface Message {
  id: string;
  role: Role;
  text: string;
  attachment?: Attachment; // Image sent by user
  generatedImage?: string; // Image generated by AI (Base64)
  timestamp: number;
}

export interface ChatSession {
  id: string;
  title: string;
  domainId: DomainId;
  messages: Message[];
  createdAt: number;
  userId: string; // Link session to user
}

// Novos tipos para memória contextual
export interface UserMemoryEntry {
  id: string;
  userId: string;
  type: 'interest' | 'knowledge_level' | 'preference' | 'goal' | 'context';
  category: string; // ex: 'programming', 'learning_style', 'project'
  key: string; // ex: 'favorite_language', 'experience_level', 'current_project'
  value: string; // ex: 'Python', 'beginner', 'e-commerce website'
  confidence: number; // 0-1, quão confiante estamos nesta informação
  lastUpdated: number;
  expiresAt?: number; // Para informações temporárias
}

export interface UserProfile {
  userId: string;
  knowledgeLevel: Record<DomainId, 'beginner' | 'intermediate' | 'advanced'>;
  interests: string[]; // Tópicos de interesse
  learningStyle: 'visual' | 'auditory' | 'kinesthetic' | 'reading' | 'mixed';
  goals: string[]; // Objetivos de aprendizado
  frequentTopics: Record<string, number>; // Tópico -> frequência
  lastActive: number;
  totalSessions: number;
  averageSessionLength: number;
}

export interface ContextualMemory {
  shortTerm: Message[]; // Últimas mensagens da sessão atual
  mediumTerm: UserMemoryEntry[]; // Informações da última semana
  longTerm: UserProfile; // Perfil consolidado do usuário
}

export enum DomainId {
  PROGRAMMING = 'programming',
  CONSULTING = 'consulting',
  THEOLOGY = 'theology',
  AGRICULTURE = 'agriculture',
  ACCOUNTING = 'accounting',
  PSYCHOLOGY = 'psychology',
}

export interface DomainConfig {
  id: DomainId;
  name: string;
  icon: string;
  color: string; // Tailwind text color class
  bgColor: string; // Tailwind bg color class
  description: string;
  systemPrompt: string;
}